/**
 * npm run graph:render
 *
 * Renders the three pipeline graphs (detection, worker, metrics) as Mermaid
 * plus an edge table, writes docs/GRAPHS.md, and refreshes the "Pipeline as a
 * graph" section of README.md between its markers. tests/test-graph-docs.ts
 * fails when the README section is stale, so the diagram cannot drift from
 * the code that declares the edges.
 */
import fs from "fs";
import { validateGraph, toMermaid, listEdges, GraphSpec } from "../src/graph/graph";
import { METRICS_GRAPH } from "../src/graph/metricsGraph";
import { buildDetectionGraph, buildWorkerGraph } from "../src/graph/pipelineGraph";

/** Dependencies are irrelevant for rendering; the topology is fixed at build time. */
const noop: any = new Proxy({}, { get: () => () => null });
export const GRAPHS: { title: string; graph: GraphSpec<any>; what: string }[] = [
  { title: "1. Detection (per newPool event)", graph: buildDetectionGraph({ ...noop, counters: { detected: 0, decided: 0, dropped: 0, notEvaluated: 0, creditHalted: 0 }, breaker: noop, decisionLog: noop, maxQueued: 0 }), what: "Runs synchronously on every detected pool. Ends by queuing the token, or by recording exactly why it was not evaluated." },
  { title: "2. Worker (per dequeued token)", graph: buildWorkerGraph({ ...noop, counters: { detected: 0, decided: 0, dropped: 0, notEvaluated: 0, creditHalted: 0 }, decisionLog: noop, shadow: { enabled: false, hasSets: false, evaluate: noop, log: noop }, paper: { enabled: false, open: noop, openCount: () => 0, log: noop }, tradingPass: null }), what: "Collects metrics (graph 3), decides, records - then everything that must not influence the decision." },
  { title: "3. Metrics collection (inside collectMetrics)", graph: METRICS_GRAPH, what: "Cheap checks first, venue-routed; the expensive holder, bundle and activity calls only for tokens still capable of passing." },
];

export function renderDocs(): string {
  const L: string[] = [];
  L.push("<!-- GENERATED by `npm run graph:render` from src/graph/*.ts - do not edit by hand -->");
  L.push("");
  let total = 0, conditional = 0;
  for (const g of GRAPHS) {
    const v = validateGraph(g.graph);
    total += v.edgeCount; conditional += v.conditionalEdges;
    L.push(`### ${g.title}`);
    L.push("");
    L.push(g.what);
    L.push("");
    L.push(`${v.nodeCount} nodes, ${v.edgeCount} edges, **${v.conditionalEdges} conditional**. Solid arrows are conditional edges (taken when their label holds, checked in order); dotted arrows are the default route.`);
    L.push("");
    L.push("```mermaid");
    L.push(toMermaid(g.graph, { direction: "TD" }));
    L.push("```");
    L.push("");
    L.push("| from | condition | to |");
    L.push("|---|---|---|");
    for (const e of listEdges(g.graph)) L.push(`| ${e.from} | ${e.conditional ? `**${e.label}**` : `_${e.label}_`} | ${e.to} |`);
    L.push("");
  }
  L.push(`**Total: ${total} edges, ${conditional} conditional** - roughly how many places a routing bug could have been hiding.`);
  return L.join("\n");
}

const README_START = "<!-- graph-section:start -->";
const README_END = "<!-- graph-section:end -->";

export function readmeSection(): string {
  return [
    README_START,
    "## Pipeline as a graph",
    "",
    "Control flow is declared as topology, not hidden in if/else: a typed State, node functions `(state) => partial state`, and an explicit edge map (`src/graph/`). `validateGraph` refuses a node nobody can reach, an edge to nowhere, or a node whose edges are all conditional; `tests/test-graph.ts` and `tests/test-pipeline-graph.ts` walk every declared edge; `tests/test-eval-goldens.ts` holds the refactor to the pre-graph collector's outputs field for field.",
    "",
    renderDocs(),
    README_END,
  ].join("\n");
}

if (require.main === module) {
  fs.mkdirSync("docs", { recursive: true });
  fs.writeFileSync("docs/GRAPHS.md", "# OPIUMO pipeline graphs\n\n" + renderDocs() + "\n");
  const readme = fs.readFileSync("README.md", "utf-8");
  const section = readmeSection();
  let next: string;
  if (readme.includes(README_START) && readme.includes(README_END)) {
    next = readme.slice(0, readme.indexOf(README_START)) + section + readme.slice(readme.indexOf(README_END) + README_END.length);
  } else {
    // First insertion: before "## Status" so it sits with the architecture notes.
    const at = readme.indexOf("## Status");
    next = at === -1 ? readme + "\n\n" + section + "\n" : readme.slice(0, at) + section + "\n\n" + readme.slice(at);
  }
  fs.writeFileSync("README.md", next);
  for (const g of GRAPHS) { const v = validateGraph(g.graph); console.log(`${g.title}: ${v.nodeCount} nodes, ${v.edgeCount} edges, ${v.conditionalEdges} conditional${v.ok ? "" : " - INVALID: " + v.problems.join("; ")}`); }
  console.log("wrote docs/GRAPHS.md and the README section");
}
